os scripts

diff --git a/os/Makefile b/os/Makefile
--- a/os/Makefile
+++ b/os/Makefile
@@ -17,7 +17,14 @@ os-image:
 	mkdir -p iso iso/boot iso/boot/grub
 	cp ./linux*/arch/x86_64/boot/bzImage ./iso/boot/bzImage
 	cp ./busybox/initramfs.cpio.gz ./iso/boot/initramfs.cpio.gz
-	@if [ -d "/sys/firmware/efi" ]; then \
+	tput setaf 4
+	@echo "What system is using the targeted machine?"
+	@echo "     [1] uefi"
+	@echo "     [2] bios"
+	@echo " -> Note that any unexpected response will lead to the selection of the system on this machine"
+	tput sgr0
+	@read kind;	\
+	if [[ ($$kind == "1") || (-d "/sys/firmware/efi" && $$kind != "2") ]]; then \
 		# your system is using uefi; \
 		echo set default=0 > ./iso/boot/grub/grub.conf; \
 		echo set timeout=10 >> ./iso/boot/grub/grub.conf; \
@@ -47,10 +54,10 @@ os-image:
 		echo "	initrd /boot/initramfs.cpio.gz" >> ./iso/boot/grub/grub.conf; \
 		echo } >> ./iso/boot/grub/grub.conf; \
 	fi
-	grub-mkrescue -o ../build/distrinet.iso iso/
+	grub-mkrescue -o ./districomp.iso iso/
 	tput setaf 2
 	@echo "OS Image done !"
-	@echo "Available on ../build/distrinet.iso"
+	@echo "Available on ./districomp.iso"
 	tput sgr0
 
 kernel:
@@ -59,6 +66,11 @@ kernel:
 	tput sgr0
 	@if [ -d ./linux* ]; then \
 		cd ./linux*; \
+		tput setaf 3; \
+		echo "In the next TUI, edit as you want, save and quit."; \
+		echo "WARNING: your display/console must be at least 19 lines by 80 columns."; \
+		read -p "Press any key to continue."; \
+		tput sgr0;	\
 		make menuconfig; \
 		make; \
 	else \
@@ -75,15 +87,15 @@ initrd:
 	tput setaf 2
 	@echo "***   Making Initrd   ***"
 	tput sgr0
-	@if [ ! -f ./networkSetup.sh ]; then \
+	@if [ ! -f $(netSetup) ]; then \
 		tput setaf 1; \
-		echo "ERROR: No networking setup script found. Make sure to have a networking setup script named ./networkSetup.sh"; \
+		echo "ERROR: No networking setup script found. Make sure to have a networking setup script on $(netSetup)"; \
 		tput sgr0; \
 		exit; \
 	fi
-	@if [ ! -f ../build/client.o ]; then \
+	@if [ ! -f $(clientO) ]; then \
 		tput setaf 1; \
-		echo "ERROR: No client found. Make sure to have client binaries under ../build/client.o"; \
+		echo "ERROR: No client found. Make sure to have client binaries under $(clientO)"; \
 		tput sgr0; \
 		exit; \
 	fi
@@ -101,8 +113,8 @@ initrd:
 	make install; \
 	cd _install; \
 	mkdir dev proc sys; \
-	cp ../../networkSetup.sh ./networkSetup.sh; \
-	cp ../../../build/client.o ./client.o; \
+	cp ../../$(netSetup) ./networkSetup.sh; \
+	cp ../../$(clientO) ./client.o; \
 	echo "#!/bin/sh" > init; \
 	echo "mount -t devtmpfs none /dev" >> init; \
 	echo "mount -t proc none /proc" >> init; \
@@ -118,4 +130,4 @@ clean:
 	tput setaf 3
 	@echo "Note: Only clean basic things, not all the files built during install. To do so, follow instructions on busybox and linux Makefile"
 	tput sgr0
-	rm -rf ./iso ./busybox/initramfs.cpio.gz ./busybox/_install ./linux*/arch/x86_64/boot/bzImage ../build/distrinet.iso
+	rm -rf ./iso ./busybox/initramfs.cpio.gz ./busybox/_install ./linux*/arch/x86_64/boot/bzImage
